---
## You can override the default chart name (i.e., .Charts.name) when desired using the following parameter.
## This is the only way to have more than one deployment of this
nameOverride: null

## Number of Hive Metastore instances.
## Following the documentation, given Hive Metastore is stateless we could have more than one instance.
## https://cwiki.apache.org/confluence/display/Hive/AdminManual+Metastore+Administration
replicaCount: 1

## Default Hive image and tag. Please build image locally before applying this.
image:
  name: andreclaudino/hive-metastore
  tag: 1.0.0-hive3
  pullPolicy: IfNotPresent

azureSorage:
  accounts: []
    # - name: 
    #   key:

hiveConfigParameters:
  - key: hive.metastore.event.db.notification.api.auth
    value: "false"
  - key: hadoop.proxyuser.hive.hosts
    value: HS2_HOST
  - key: hadoop.proxyuser.hive.groups
    value: "*"
  - key: datanucleus.autoStartMechanism
    value: SchemaTable

env:
  HIVE_DB_EXTERNAL: "false"
  HIVE_WAREHOUSE_DIR: file:///tmp/
  HIVE_DB_HOST: "hostname:5432"
  HIVE_DB_NAME: hive_metastore_db
  HIVE_DB_USER: hive-admin
  HIVE_DB_PASS: hive-pass


## Resource requests and limits: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi

service:
  type: ClusterIP
  port: 9093

## Auto-scaling (hpa) configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90